#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/Genesis-Plus-GX-Paprium-PS2"
REPO_FOLDER="genesis_plus_gx_libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## Compile core using native platform=ps2 support
make -j $PROC_NR platform=ps2 clean || { exit 1; }
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/genesis_plus_gx_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p genesis_plus_gx_libretro
cp -f "$REPO_FOLDER/genesis_plus_gx_libretro_ps2.a" genesis_plus_gx_libretro_ps2.a || { exit 1; }