#!/bin/bash
# package.sh

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/mame2000-libretro.git"
REPO_FOLDER="mame2000-libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## Patch sjlj.c for PS2 compatibility to handle sigsetjmp argument counts properly
if [ -f "src/libretro/libretro-common/libco/sjlj.c" ]; then
    sed -i 's/sigsetjmp(\([^,]*\), [^)]*)/setjmp(\1)/g' src/libretro/libretro-common/libco/sjlj.c
    sed -i 's/siglongjmp/longjmp/g' src/libretro/libretro-common/libco/sjlj.c
fi

## Compile core using native platform=ps2 support with required signal overrides
make -j $PROC_NR platform=ps2 CFLAGS="-DSA_ONSTACK=0 -Dsigjmp_buf=jmp_buf" clean || { exit 1; }
make -j $PROC_NR platform=ps2 CFLAGS="-DSA_ONSTACK=0 -Dsigjmp_buf=jmp_buf" || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile from the root of REPO_FOLDER
cp -f "$REPO_FOLDER/mame2000_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p mame2000-libretro
cp -f "$REPO_FOLDER/mame2000_libretro_ps2.a" mame2000-libretro/mame2000-libretro_ps2.a || { exit 1; }
