#!/bin/bash
# package.sh

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/mame2000-libretro.git"
REPO_FOLDER="mame2000-libretro"
BRANCH_NAME="ps2-gcc9"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## Compile core using native platform=ps2 support with required signal overrides
make -j $PROC_NR platform=ps2 CFLAGS="-DSA_ONSTACK=0 -Dsiglongjmp=longjmp" clean || { exit 1; }
make -j $PROC_NR platform=ps2 CFLAGS="-DSA_ONSTACK=0 -Dsiglongjmp=longjmp" || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/mame2000-libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p beetle-vb-libretro
cp -f "$REPO_FOLDER/mame2000-libretro_ps2.a" mame2000-libretro_ps2.a || { exit 1; }