#!/bin/bash
# package.sh

PROC_NR=$(getconf _NPROCESSORS_ONLN)

##REPO_URL="https://github.com/Stayhye/mame2000-libretro.git"
REPO_URL="https://github.com/libretro/mame2000-libretro.git"
REPO_FOLDER="mame2000-libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## 1. Wipe out any pre-existing object files to prevent caching stale libco.o
find . -name "*.o" -delete
find . -name "*.a" -delete

## 2. Completely replace libco.c to force sjlj backend for MIPS/PS2
LIBCO_SELECTOR="src/libretro/libretro-common/libco/libco.c"
if [ -f "$LIBCO_SELECTOR" ]; then
    cat << 'EOF' > "$LIBCO_SELECTOR"
/*
  libco auto-selection override for PS2
*/
#if defined(__mips__) || defined(_PS2)
  #include "sjlj.c"
#elif defined _MSC_VER
  #include "fiber.c"
#elif defined __GNUC__
  #if defined __i386__
    #include "x86.c"
  #elif defined __amd64__
    #include "amd64.c"
  #else
    #include "sjlj.c"
  #endif
#else
  #include "sjlj.c"
#endif
EOF
fi

## 3. Patch sjlj.c to remove any signal dependencies completely
SJLJ_FILE="src/libretro/libretro-common/libco/sjlj.c"
if [ -f "$SJLJ_FILE" ]; then
    sed -i 's/sigsetjmp(\([^,]*\), [^)]*)/setjmp(\1)/g' "$SJLJ_FILE"
    sed -i 's/siglongjmp/longjmp/g' "$SJLJ_FILE"
    # Neutralize any sigaltstack or sigaction code paths in sjlj.c
    sed -i 's/struct sigaction/int /*struct sigaction*//g' "$SJLJ_FILE"
    sed -i 's/sigaltstack/no_sigaltstack/g' "$SJLJ_FILE"
fi

## 4. Build with clean target, disabling cheats to prevent missing symbol errors
make -j $PROC_NR platform=ps2 CHEAT=0 CFLAGS="-DSA_ONSTACK=0 -Dsigjmp_buf=jmp_buf -UHAVE_CHEATS" clean || { exit 1; }
make -j $PROC_NR platform=ps2 CHEAT=0 CFLAGS="-DSA_ONSTACK=0 -Dsigjmp_buf=jmp_buf -UHAVE_CHEATS" || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/mame2000_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p mame2000-libretro
cp -f "$REPO_FOLDER/mame2000_libretro_ps2.a" mame2000-libretro/mame2000-libretro_ps2.a || { exit 1; }