#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/MBA.mini-libretro"
REPO_FOLDER="MBA.mini_libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; } 

# Explicitly override CFLAGS, CXXFLAGS, and INCPATH in the makefile for zlib/ports
if [ -f "makefile" ]; then
    sed -i 's|CFLAGS   +=|CFLAGS   += -I/usr/local/ps2dev/ports/include|g' makefile
    sed -i 's|CXXFLAGS +=|CXXFLAGS += -I/usr/local/ps2dev/ports/include|g' makefile
    sed -i 's|INCPATH  +=|INCPATH  += -I/usr/local/ps2dev/ports/include|g' makefile
    echo "CFLAGS += -I/usr/local/ps2dev/ports/include" >> makefile
    echo "CXXFLAGS += -I/usr/local/ps2dev/ports/include" >> makefile
elif [ -f "Makefile" ]; then
    sed -i 's|CFLAGS   +=|CFLAGS   += -I/usr/local/ps2dev/ports/include|g' Makefile
    sed -i 's|CXXFLAGS +=|CXXFLAGS += -I/usr/local/ps2dev/ports/include|g' Makefile
    sed -i 's|INCPATH  +=|INCPATH  += -I/usr/local/ps2dev/ports/include|g' Makefile
    echo "CFLAGS += -I/usr/local/ps2dev/ports/include" >> Makefile
    echo "CXXFLAGS += -I/usr/local/ps2dev/ports/include" >> Makefile
fi

## Compile core using native platform=ps2 support with direct make variable overrides
make -j $PROC_NR platform=ps2 CFLAGS="-O2 -I/usr/local/ps2dev/ports/include" CXXFLAGS="-O2 -I/usr/local/ps2dev/ports/include" INCPATH="-I/usr/local/ps2dev/ports/include" clean || { exit 1; }
make -j $PROC_NR platform=ps2 CFLAGS="-O2 -I/usr/local/ps2dev/ports/include" CXXFLAGS="-O2 -I/usr/local/ps2dev/ports/include" INCPATH="-I/usr/local/ps2dev/ports/include" || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/MBA.mini_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

# Prevent file/directory collision
if [ -f "MBA.mini_libretro" ]; then
    rm -f MBA.mini_libretro
fi

mkdir -p MBA.mini_libretro
cp -f ./libretro_ps2.a MBA.mini_libretro/MBA.mini_libretro_ps2.a || { exit 1; }