#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/MBA.mini-libretro"
REPO_FOLDER="MBA.mini_libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; } 

# Fix GCC version check script/makefile command that crashes bc (e.g. empty or floating point version string)
if [ -f "makefile" ]; then
    sed -i 's/shell gcc/shell echo 11/g' makefile
    sed -i 's/shell g++/shell echo 11/g' makefile
    sed -i 's/`gcc/`echo 11/g' makefile
    sed -i 's/`g++/`echo 11/g' makefile
elif [ -f "Makefile" ]; then
    sed -i 's/shell gcc/shell echo 11/g' Makefile
    sed -i 's/shell g++/shell echo 11/g' Makefile
    sed -i 's/`gcc/`echo 11/g' Makefile
    sed -i 's/`g++/`echo 11/g' Makefile
fi

# Ensure include paths for emulator core and zlib are fully registered in the makefile
if [ -f "makefile" ]; then
    sed -i 's|INCPATH  +=|INCPATH  += -I/usr/local/ps2dev/ports/include -Isrc/emu -Isrc/lib/util |g' makefile
    sed -i 's|CFLAGS   +=|CFLAGS   += -I/usr/local/ps2dev/ports/include -Isrc/emu -Isrc/lib/util |g' makefile
elif [ -f "Makefile" ]; then
    sed -i 's|INCPATH  +=|INCPATH  += -I/usr/local/ps2dev/ports/include -Isrc/emu -Isrc/lib/util |g' Makefile
    sed -i 's|CFLAGS   +=|CFLAGS   += -I/usr/local/ps2dev/ports/include -Isrc/emu -Isrc/lib/util |g' Makefile
fi

## Compile core using native platform=ps2 support
make -j $PROC_NR platform=ps2 clean || { exit 1; }
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/MBA.mini_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

# Prevent file/directory collision
if [ -f "MBA.mini_libretro" ]; then
    rm -f MBA.mini_libretro
fi

mkdir -p MBA.mini_libretro
cp -f ./libretro_ps2.a MBA.mini_libretro/MBA.mini_libretro_ps2.a || { exit 1; }