#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

## Determine the maximum number of processes that Make can work with.
PROC_NR=$(getconf _NPROCESSORS_ONLN)

## Download the source code.
REPO_URL="https://github.com/Stayhye/beetle-wswan-libretro.git"
REPO_FOLDER="mednafen-wswan-libretro"
BRANCH_NAME="master"
if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## Compile core using native platform=ps2 support
make -j $PROC_NR platform=ps2 clean || { exit 1; }
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "beetle-wswan-libretro/mednafen_wswan_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p mednafen-wswan-libretro
cp -f "beetle-wswan-libretro/mednafen_wswan_libretro_ps2.a" mednafen-wswan-libretro_ps2.a || { exit 1; }