#!/bin/bash
# package.sh for NJEMU-libretro on PS2

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/NJEMU-libretro"
REPO_FOLDER="njemu-libretro"
BRANCH_NAME="master"

# Choose which system to compile: cps1, cps2, mvs, or ncdz
SYSTEM="cps2"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; } 

## Compile core using native platform=ps2 support and selected SYSTEM
make -j $PROC_NR platform=ps2 SYSTEM=$SYSTEM clean || { exit 1; }
make -j $PROC_NR platform=ps2 SYSTEM=$SYSTEM || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/njemu_${SYSTEM}_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p njemu-libretro
cp -f "$REPO_FOLDER/njemu_${SYSTEM}_libretro_ps2.a" njemu_${SYSTEM}_libretro_ps2.a || { exit 1; }