#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/potator"
REPO_FOLDER="potator"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }

## Compile core using native platform=ps2 support (skipping clean)
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
ARCHIVE_NAME=$(basename $(find "$REPO_FOLDER" -maxdepth 1 -name "*_ps2.a" | head -n 1))
if [ -z "$ARCHIVE_NAME" ]; then
    echo "Error: Could not find generated static archive (*_ps2.a)"
    exit 1
fi

cp -f "$REPO_FOLDER/$ARCHIVE_NAME" ./libretro_ps2.a || { exit 1; }

mkdir -p potator
if [ "$REPO_FOLDER/$ARCHIVE_NAME" != "potator/potator-libretro_ps2.a" ]; then
    cp -f "$REPO_FOLDER/$ARCHIVE_NAME" potator/potator-libretro_ps2.a || { exit 1; }
fi