#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

# 1. Install host OpenGL headers required by libretro-common's glsym generator
if command -v apt-get &> /dev/null; then
    if [ "$EUID" -eq 0 ]; then
        apt-get update && apt-get install -y libgl1-mesa-dev mesa-common-dev || true
    elif command -v sudo &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev mesa-common-dev || true
    fi
fi

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/libretro-vecx"
REPO_FOLDER="vecx_libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; }
git submodule update --init --recursive || { exit 1; }

# 2. Fix legacy 'einline' macro definition for modern GCC compilers in e6809.c
if [ -f "e6809.c" ] && ! grep -q "#define einline" e6809.c; then
    sed -i '1i #define einline static inline' e6809.c
fi

## Compile core using native platform=ps2 support
make -j $PROC_NR platform=ps2 clean || { exit 1; }
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/vecx_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p vecx_libretro
cp -f "$REPO_FOLDER/vecx_libretro_ps2.a" vecx_libretro_ps2.a || { exit 1; }