#!/bin/bash
# package.sh by Francisco Javier Trujillo Mata (fjtrujy@gmail.com)

PROC_NR=$(getconf _NPROCESSORS_ONLN)

REPO_URL="https://github.com/Stayhye/vemulator-libretro"
REPO_FOLDER="vemulator_libretro"
BRANCH_NAME="master"

if test ! -d "$REPO_FOLDER"; then
    git clone --recurse-submodules --depth 1 -b $BRANCH_NAME $REPO_URL $REPO_FOLDER || { exit 1; }
fi

cd $REPO_FOLDER || { exit 1; }
git fetch origin
git reset --hard origin/${BRANCH_NAME}
git checkout ${BRANCH_NAME} || { exit 1; } 

# Create sys/mman.h directly in the repository root so the existing -I. flag finds it automatically
mkdir -p sys
cat << 'EOF' > sys/mman.h
#ifndef __PS2_SYS_MMAN_H__
#define __PS2_SYS_MMAN_H__

#include <sys/types.h>

#define PROT_READ       0x1
#define PROT_WRITE      0x2
#define PROT_EXEC       0x4
#define MAP_SHARED      0x01
#define MAP_PRIVATE     0x02
#define MAP_ANONYMOUS   0x20
#define MAP_FAILED      ((void *)-1)

#ifdef __cplusplus
extern "C" {
#endif

static inline void* mmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset) {
    return MAP_FAILED;
}

static inline int munmap(void *addr, size_t length) {
    return -1;
}

static inline int msync(void *addr, size_t length, int flags) {
    return -1;
}

#ifdef __cplusplus
}
#endif

#endif
EOF

## Compile core using native platform=ps2 support
make -j $PROC_NR platform=ps2 clean || { exit 1; }
make -j $PROC_NR platform=ps2 || { exit 1; }

cd .. || { exit 1; }

## Copy the proper static archive generated by the Makefile
cp -f "$REPO_FOLDER/vemulator_libretro_ps2.a" ./libretro_ps2.a || { exit 1; }

mkdir -p vemulator_libretro
cp -f "$REPO_FOLDER/vemulator_libretro_ps2.a" vemulator_libretro/vemulator_libretro_ps2.a || { exit 1; }