name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  cores:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_owner: [ps2dev]
        core_opts: [
          [libretro-prboom, prboom_libretro_ps2],
          [libretro-samples, test_libretro_ps2],
          [picodrive, picodrive_libretro_ps2],
          [ecwolf, ecwolf_libretro_ps2],
          [snes9x2002, snes9x2002_libretro_ps2],
          [libretro-lutro, lutro_libretro_ps2],
          [gpsp, gpsp_libretro_ps2],
          [libretro-fceumm, fceumm_libretro_ps2],
         ]

    container: ${{ matrix.docker_owner }}/ps2dev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash
    
    # To be removed once ps2_drivers is part of PS2DEV
    - name: Install ps2_drivers lib
      run: |
        git clone https://github.com/fjtrujy/ps2_drivers.git
        cd ps2_drivers
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install
    
    - name: Compile project
      run: |
        ./prepare_release.sh
        ./prepare_retroarch.sh
        ./cores/${{ matrix.core_opts[0] }}.sh
        ./generate_retroarch.sh ${{ matrix.core_opts[0] }} ${{ matrix.core_opts[1] }}

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: RA-${{ matrix.docker_owner }}-${{ steps.slug.outputs.sha8 }}
        path: RA/


  libretro-salamander:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_owner: [ps2dev]

    container: ${{ matrix.docker_owner }}/ps2dev:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base git bash

    # To be removed once ps2_drivers is part of PS2DEV
    - name: Install ps2_drivers lib
      run: |
        git clone https://github.com/fjtrujy/ps2_drivers.git
        cd ps2_drivers
        make -j $(getconf _NPROCESSORS_ONLN) clean
        make -j $(getconf _NPROCESSORS_ONLN)
        make -j $(getconf _NPROCESSORS_ONLN) install
    
    - name: Compile project
      run: |
        ./prepare_release.sh
        ./prepare_retroarch.sh
        ./generate_salamander.sh

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: RA-${{ matrix.docker_owner }}-${{ steps.slug.outputs.sha8 }}
        path: RA/


  libretro-info-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_owner: [ps2dev]

    steps:
    - uses: actions/checkout@v3

    - name: Compile project
      run: |
        ./prepare_release.sh
        ./libretro-core-info.sh

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: RA-${{ matrix.docker_owner }}-${{ steps.slug.outputs.sha8 }}
        path: RA/

    